#!/usr/bin/with-contenv bash

ADDPARAM="-Dupnp.config.address=${SERVERIP} -Dserver.port=${SERVERPORT}"
VERSION="$(curl -sX GET https://api.github.com/repos/bwssytems/ha-bridge/releases/latest | grep 'tag_name' | cut -d\" -f4)"
VERSION=${VERSION:1}
cd /config
exec \
        java -jar ${ADDPARAM} ha-bridge-"$VERSION".jar 2>&1 | tee /config/ha-bridge.log
